### ISSUE TITLE
Cannot update vault item

### ISSUE THREAD

**Issue by mahe-kl** [Nordstrom/chef-vault#116]
We have a vault item that contains a server ssl certificate. A few days ago we became unable to add new admins to the vault item or update it's serach query. If one already is admin or client to the item, one can decrypt it just fine.

knife vault update -VV vault item -A some_admin prints this:
```
/home/filou/.chefdk/gem/ruby/2.1.0/gems/chef-vault-2.2.4/lib/chef-vault/item_keys.rb:36:in `add': undefined method `<<' for #<Hash:0x000000044282f0> (NoMethodError)
	from /home/filou/.chefdk/gem/ruby/2.1.0/gems/chef-vault-2.2.4/lib/chef-vault/item.rb:79:in `block in admins'
	from /home/filou/.chefdk/gem/ruby/2.1.0/gems/chef-vault-2.2.4/lib/chef-vault/item.rb:75:in `each'
	from /home/filou/.chefdk/gem/ruby/2.1.0/gems/chef-vault-2.2.4/lib/chef-vault/item.rb:75:in `admins'
	from /home/filou/.chefdk/gem/ruby/2.1.0/gems/chef-vault-2.2.4/lib/chef/knife/vault_update.rb:72:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:174:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:34:in `load'
	from /opt/chefdk/bin/knife:34:in `<main>'
```

and knife vault update -VV vault item -A some_admin -S search_query prints this:
```
/home/filou/.chefdk/gem/ruby/2.1.0/gems/chef-vault-2.2.4/lib/chef-vault/item_keys.rb:36:in `add': undefined method `<<' for {"0"=>"some_client", "1"=>"some_other_client"}:Hash (NoMethodError)
	from /home/filou/.chefdk/gem/ruby/2.1.0/gems/chef-vault-2.2.4/lib/chef-vault/item.rb:47:in `block in clients'
	from /home/filou/.chefdk/gem/ruby/2.1.0/gems/chef-vault-2.2.4/lib/chef-vault/item.rb:42:in `each'
	from /home/filou/.chefdk/gem/ruby/2.1.0/gems/chef-vault-2.2.4/lib/chef-vault/item.rb:42:in `clients'
	from /home/filou/.chefdk/gem/ruby/2.1.0/gems/chef-vault-2.2.4/lib/chef/knife/vault_update.rb:71:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:174:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:34:in `load'
	from /opt/chefdk/bin/knife:34:in `<main>'
```

Both command work just fine with other item in the same vault that was created at the same time.

I have tried removing by hand some clients and admins no longer present on the chef-server, the problem itself started before that.

I have also tried with multiple combinations of vault, ruby and chef versions, with made no significant difference to the situation.

Current tool versions: 
knife -v -> Chef: 11.14.0.rc.2
chef-vault 2.2.4
ruby -v -> ruby 2.1.1p76

**Comment by jf647** [comment]
I've been trying to repro this, and I can't figure out whether it's a chef-vault bug or a corrupted vault.

The stacktrace says that we're trying to call split on an array, when that part of the code expects to have been passed a string.

In the _keys data bag, the admins entry should be an array of names of admin users.  rotate_keys! iterates over this array, adding/updating each admin to the keys data bag.

To end up with an array inside the iterator sounds like the bag is in some way corrupt, like it has this:

```json
  "admins": [[
    "0",
    "mahe"
  ]]
```
instead of this:

```json
  "admins": [
    "0",
    "mahe"
  ]
```

We could just call #flatten on admins before iterating over it, but if this is a bag that was broken outside of chef-vault somehow, it seems unnecessary.

Can you check some of your data bags using `knife data bag show vault item_keys` and see what the admins key looks like?  Array or Array-of-Array?

**Comment by jf647** [comment]
Were you able to check what the contents of the keys data bag looked like?  I'd like to close this before work on the next release starts if there's no further research to be done.

**Comment by jf647** [comment]
Closing for lack of feedback
