### ISSUE TITLE
[Databag]/[Databag Item]  is not encrypted with your public key.  Contact an administrator of the vault item to encrypt for you!

### ISSUE THREAD

**Issue by msivarami** [Nordstrom/chef-vault#137]
Created Vault using 
knife vault create databag_name databag_item -J databag_file.json -A root --mode client
Created Chef Vault using Chef Server user - root.
Able to create databag item successfully, without issues. Encryoted using root.pem file.
Created a recipe with the below details: 
_______________________________________________________________
 include_recipe 'chef-vault'
 mydata = ChefVault::Item.load('databag_name', 'databag_item')
   Chef::Log.info("The decrypted password is '#{mydata['username']}' ")
_______________________________________________________________

Uploaded the cookbook and ran chef-client.
This is throwing the error : 
[Databag]/[Databag Item]  is not encrypted with your public key.  Contact an administrator of the vault item to encrypt for you!

I am not sure where i have made a mistake.
Please suggest!!

**Comment by jf647** [comment]
You encrypted the bag for your user, but not for any nodes.  Nodes have their own client identities with public keys (stored on the chef server) and private keys (stored in /etc/chef/client.pem).

You need to use '-S SOLR_QUERY' to search for clients so that they can decrypt the vault item.  You can use that at vault creation time, but having created the vault you can pass it to 'knife vault update' to change the query used to find clients.

**Comment by rguruju** [comment]
Checking in the data bag with a dummy check in should also solve this problem. That will re run the knife search role again and so, the client(in this case, node is the client) will be able to find the databag.

**Comment by SrikarshVardhanreddyKolanu** [comment]
@jf647 Hi am also facing same error is there any knife command which can be used to import public key of my client to my data bag item?
