### ISSUE TITLE
I am an Admin but I cannot modify the vault item

### ISSUE THREAD

**Issue by mdw233** [Nordstrom/chef-vault#138]
Hi All,

I created a chef-vault item awhile back.  It is called _encrypted\_data_ and has an item called _userpasswords_.  That item has a list of usernames/passwords used for configuring Windows services.

My Chef user is in the admins list - I verified that by looking at the __admins__ value in the _userpasswords\_keys_ item.  However, I do not have a separate entry in the _userpasswords\_keys_ for my client (machine).

So - my user is an admin but my node/workstation doesn't have a key.  How can I encrypt the databag so that I can edit and use it from my workstation?  I feel like as an admin, I should be able to edit it with my user.

When I run the following command:
`knife vault edit encrypted_data userpasswords`

I get the following error:
`ERROR: ChefVault::Exceptions::SecretDecryption: encrypted_data/userpasswords is not encrypted with your public key.  Contact an administrator of the vault item to encrypt for you!`

**Comment by jf647** [comment]
When you use knife to access a vault, you are using your personal username and key (~/.chef/$USER.pem typically), referenced from the 'node_name' and 'client_key' parameters in knife.rb:

```ruby
user_name = ENV['USER'] || ENV['USERNAME']
node_name                user_name
client_key               "#{ENV['HOME']}/.chef/#{user_name}.pem"
knife[:vault_mode] = 'client'
knife[:vault_admins] = %w(foo bar baz)
```

When you use the ChefVault ruby classes to access a vault in a recipe, you are using your workstation's key (/etc/chef/client.pem typically), referenced from 'client_key' in client.rb.

On most of my boxes, 'node_name' and 'client_key' aren't even set in client.rb because they are [defaulted](https://docs.chef.io/config_rb_client.html).

So the vault doesn't need to be encrypted for your management workstation, only for your personal username and the nodes who want to access it (via a SOLR query string).

If you're getting the 'is not encrypted for you' error, then you're probably telling knife (perhaps inadvertently) to use your workstation key, not your personal key.

**Comment by mdw233** [comment]
Thanks for the fast response!

Is there an easy way to tell knife to use my personal key rather than my workstation key when accessing a vault?

**Comment by jf647** [comment]
That snippet I pasted contains the relevant lines from my ~/.chef/knife.rb file to make it do just that.

knife reads config from knife.rb, whereas chef-client reads config from client.rb.  I think knife might fall back to client.rb if knife.rb is not found, but generally you don't want that.

I have ~/.chef/knife.rb set up with the above snippet (plus many more things - go read the [knife.rb docs](https://docs.chef.io/config_rb_knife.html) for everything you can put in there).  I also have my personal key in ~/.chef/james.pem (assuming that my username on the box is 'james').

You can hardcode the paths if you prefer - we distribute a common knife.rb to our internal users which uses environment variables to do the right thing for all users.

**Comment by jf647** [comment]
Did this resolve your issue?  Can I close this, or do you have further questions?

**Comment by mdw233** [comment]
You can close this.  I never fully resolved it, but I am quite certain that
I caused a problem for myself by deleting my key out of the _keys item.  I
was able to straighten myself out by having another admin regenerate a key
for my client.

On Thu, Feb 26, 2015 at 11:52 AM, James FitzGibbon <notifications@github.com
