### ISSUE TITLE
How do I automatically add a new client/node with cloudformation or auto scaling?

### ISSUE THREAD

**Issue by akshah123** [Nordstrom/chef-vault#147]
Hi,

I apologize in advance for creating an issue for a question but I don't know how else to reach out about this.

I have aws cloud formation setup that creates an instance which would need access to the secrets.  However, my recipe fails with message "ERROR: {my key} is not encrypted with your public key.  Contact an administrator of the vault item to encrypt for you!"

It fails because the node/client for the new instance doesn't have access to it. However, I can't give it access before its created.  How do I get around this problem where new chef clients/nodes are created on demand without a manual intervention?

Thanks.

**Comment by jf647** [comment]
There is no simple solution for this.  If you use Chef server 12, you can provide the private key for a node ahead of time and make sure that that specific client.pem lands on the autoscaled node.  If you use knife bootstrap, it now has support for refreshing a vault item before the initial chef-client run.

The long-term plan (chef-vault v3.0) is to make Chef-Vault pluggable and let people write gems that handle keys in ways that work for them.  Using the node's public key on Chef 11 or earlier will always have the problem that you describe.

**Comment by akshah123** [comment]
@jf647 thanks so much for responding quickly.  I understand your point. Is it possible to perhaps use a specified secrets file while loading and an item from chef-vault?

I am asking because, for now, I am thinking I will have a step that retrieves a shared key (per group of machine) from s3 that can be used to load the items.  I can add a step in cloud formation that loads up the shared key which I can use in recipe on the first chef-client run.

**Comment by jf647** [comment]
If you use the ruby classes directly, this should be possible.

If you subclass ChefVault::Item and override the secret method to do the same thing but with another key then everything else should fall into place.

If you look at the default implementation it always gets the per-node encrypted secret that matches the node name and uses the node's private key.

Because this would encourage people to bake private keys into images, I've shied away from spelling out the particulars, but until 3.0 is a real thing, it might be a stopgap for you.

**Comment by akshah123** [comment]
Thanks.
