### ISSUE TITLE
Allow clients (without a node) to be returned via searches.

### ISSUE THREAD

**Issue by dblessing** [Nordstrom/chef-vault#150]
We would like the ability to use a Chef client key to use in certain circumstances where it isn't feasible to refresh a vault each time a new node is added. For example, this could be used with AWS to drop a client key in an S3 bucket (protected via IAM roles) that would allow the EC2 instances to pull the encryption key from the bucket and decrypt a vault. However, since it's still a vault and not an encrypted data bag there can still be other nodes/clients and admins on the vault. It's much more flexible than a simple encrypted data bag.

This would probably be a simple implementation - allow the search query to return the client index, too, or provide another query flag to enable searching client index.

**Comment by dblessing** [comment]
This also carries the implication that chef vault must allow optionally specifying a secret as opposed to using the client's key.

**Comment by jf647** [comment]
The planned revamp for 3.0 will introduce a pluggable architecture, which should allow this quite easily.  If you look at the Milestones under issues, we're trying to close up feature requests that can implemented without too much internal change for the next release, 2.6.  While querying the client index isn't hard, 

In the meantime, you might want to look at the approach suggested in #147, which may do what you want.

**Comment by jf647** [comment]
We're going to try to dedicate some time to getting 2.6 out and I want to make sure I understand the use case in the event that this is easier to implement properly than I first thought.  Could you provide an example including pseudo-recipe code that you'd use if chef-vault did what you want?

**Comment by jf647** [comment]
When you say "chef vault must allow optionally specifying a secret as opposed to using the client's key", would it still work if you provided the path to a pem file?  Or are you looking for a three-arg form of load in which you could specify the plaintext shared secret for the encrypted data bag?

**Comment by dblessing** [comment]
@jf647 A path to a key would be fine. As for code in recipe I don't envision anything being different except the part where a key/key path is specified. 

Does this answer all the questions?

**Comment by jf647** [comment]
I think I've got a way to implement this without a breaking change, though it wouldn't involve changing the search query.  We already try to load admins as nodes first and clients second, so I think you can just pass your special client name as an admin.

Calling them admins is a bit of a misnomer - they should perhaps be called 'api users'.  Nominally an admin also has permissions to read the public key of other clients and api users and to write to the data bag, but from a chef-vault perspective they're identical.

Changing how the search query works would be a big change because now we'd have to store both queries in the keys bag, add another command line switch, process both queries on vault refresh, etc.

So, my idea is to add an optional third hash arg to ChefVault::Item::load and ChefVault::Item.new that lets you override the node name from the default of `Chef::Config[:node_name]` and the client key path from the default of `Chef::Config[:node_name]`.

I think that will work, though I won't know for sure until I get into implementation.

**Comment by jf647** [comment]
I've pushed a branch that hopefully does what you need:

https://github.com/Nordstrom/chef-vault/tree/issue_150_allow_client_name_and_key_path_override

Can you take a look and gives some feedback?  I'm hoping to get 2.6.0 out the door this week if possible.

Thanks

**Comment by jf647** [comment]
Fixed in 2.6.0 released to rubygems today

**Comment by dblessing** [comment]
@jf647 thanks for releasing this. Sorry I couldn't give feedback quicker. We'll try as soon as possible
