### ISSUE TITLE
Unable to create a chef vault secret from a recipe

### ISSUE THREAD

**Issue by chirag-jog** [Nordstrom/chef-vault#154]
Hello, 
I am trying to run create a chef vault secret from a recipe. I get a permission denied. I have tried different things including giving specific update permissions to the node/client on that specific databag but to no avail.

Here is the complete stacktrace and error: https://gist.github.com/chirag-jog/1aebe628bd6ddcf1c91c

**Comment by jf647** [comment]
The problem isn't access to the data bag, it's access to reading the public key of the user in order to encrypt the secret.

```
[2015-05-05T19:49:25+00:00] DEBUG: Initiating GET to https://api.opscode.com/organizations/rm_001/users/chiragjog
...
[2015-05-05T19:49:25+00:00] DEBUG: HTTP 1.1 403 Forbidden
```

For support with the `chef_vault_secret` helper, you should open an issue against [that cookbook](https://github.com/opscode-cookbooks/chef-vault) (which was written by Chef, not by Nordstrom).

Try doing the equivalent create from the node using `knife vault create` from the node - if that fails with permission denied, I expect the helper will fail as well.

**Comment by chirag-jog** [comment]
Hi,
Thanks for responding.
I tried doing the same via the chef-vault gem and it still fails.

chef:recipe > item = ChefVault::Item.new("test", "test_data_item")
 => data_bag_item["test", "test_data_item", {"id"=>"test_data_item"}]
chef:recipe > item.raw_data = ({'id'=>'item', 'aa'=>'bb'})
 => {"id"=>"item", "aa"=>"bb"}
chef:recipe > item.admins(node.name)
WARNING: ubuntu14.clogeny.dev not found in users, trying clients.
 => ["ubuntu14.clogeny.dev"]
chef:recipe > item.save()
Net::HTTPServerException: 403 "Forbidden"
from /opt/chef/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
from /opt/chef/embedded/apps/chef/lib/chef/http.rb:145:in `request'
from /opt/chef/embedded/apps/chef/lib/chef/http.rb:126:in `post'
from /opt/chef/embedded/apps/chef/lib/chef/data_bag.rb:159:in `create'
from
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.5.0/lib/chef-vault/item_keys.rb:81:in
`rescue in save'
from
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.5.0/lib/chef-vault/item_keys.rb:75:in
`save'
from
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.5.0/lib/chef-vault/item.rb:168:in
`save'
from (irb#1):21
chef:recipe >



How do i get the client to create a secret via the recipe?


--
Regards,

[image: Clogeny logo square]

*Chirag Jog*
VP - Engineering,

Clogeny Technologies Pvt. Ltd.
(India) +91-9766619440 | (US) +1-408-598-1792

Skype: chirag.jog
http://www.clogeny.com

[image: cid:image002.png@01D00EEB.61B21AB0]
<https://www.linkedin.com/company/clogeny>  [image:
cid:image003.png@01D00EEB.61B21AB0]
<https://www.facebook.com/pages/Clogeny-Technologies-Pvt-Limited/151746528245744>
  [image: cid:image004.png@01D00EEB.61B21AB0] <https://twitter.com/clogeny>

**Comment by jf647** [comment]
This isn't really a problem with chef-vault itself: you are trying to change an object on your Chef server that you don't have permission to access.  From what you pasted, I can't even tell what you were trying to access when you received a 403 response.

Generally speaking, nodes cannot read client objects other than their own.  In order to create or update a vault, you need to be able to read the public keys of all clients (nodes and users) who you want to decrypt it, and you need to be able to write to the data bag item and the side-along _keys data bag item.  If any of those things cannot be accessed, then you won't be able to create the vault.

In the gist you posted, your problem is that the machine trying to create the vault can't read the public key of chiragjog.  I expect that you can't use `knife client show chiragjog` from that node either.

Until all those permissions are fixed, you won't be able to do what you're trying to.  But this is an issue with how your org's permissions are set up, not with chef-vault.

**Comment by chirag-jog** [comment]
Yes, makes sense. I had to explicitly give the client permissions to create
data bags or given it admin permissions (incase of open source chef) and
now it works.

Thanks for the help!

--
Regards,

[image: Clogeny logo square]

*Chirag Jog*
VP - Engineering,

Clogeny Technologies Pvt. Ltd.
(India) +91-9766619440 | (US) +1-408-598-1792

Skype: chirag.jog
http://www.clogeny.com

[image: cid:image002.png@01D00EEB.61B21AB0]
<https://www.linkedin.com/company/clogeny>  [image:
cid:image003.png@01D00EEB.61B21AB0]
<https://www.facebook.com/pages/Clogeny-Technologies-Pvt-Limited/151746528245744>
  [image: cid:image004.png@01D00EEB.61B21AB0] <https://twitter.com/clogeny>
