### ISSUE TITLE
`ChefVault::Item` should not define `#keys` method.

### ISSUE THREAD

**Issue by phene** [Nordstrom/chef-vault#158]
`ChefVault::Item` inherits from `Chef::DataBagItem`, which delegates other methods to the inner `Hash`. Users of Chef expect a DataBagItem to act like a hash and be able to call methods like `keys` to get a list of keys in the data bag item. I was very surprised to find it returning a `ChefVault::ItemKeys` object. Can this attribute be renamed to something like `secret_keys` or `vault_keys` or something else so that `Hash#keys` doesn't get overridden?

**Comment by jf647** [comment]
Because #keys is a public accessor, we could look at changing this in the next major release.  That is a major re-write to make things pluggable, and may result in `ChefVault::Item.is_a?(Chef::DataBagItem)` no longer being true.

I could add a #raw_data_keys method in that would do what you want, with it becoming an alias for #keys once v3.0.0 is done.

**Comment by phene** [comment]
I've created a intermediate method that decides whether to use `data_bag_item` or `ChefVault::Item.load` and just gone ahead and called `.to_hash` on whichever I end up using. Creating an alternate method for `keys` is not at all an agreeable solution, as the whole point is to maintain API consistency.
