### ISSUE TITLE
Permission Issue - Missing Read Permission

### ISSUE THREAD

**Issue by nhudacin** [Nordstrom/chef-vault#171]
First, great job on this!! Really neat tool. 

Obviously I'm a bit new to this tool and I'm struggling a bit to get up and running. The examples and the demo is great. I used both markdown documents extensively. I think I have everything working ok, now I'm just trying to incorporate chef-vault into our CI system. 

I'm bootstrapping a windows node for some automated testing. It looks like the knife-windows module isn't fully supporting chef-vault just yet, I entered this issue today: https://github.com/chef/knife-windows/issues/237 which means I have to bootstrap a node, refresh the vault, then add a role to the node, then force a client run (unless anyone has any better suggestions). I wish I was able to force a vault refresh before the first client run on the node. 

Anyway.. I keep getting this error: 

knife vault update passwords root -S "role:*"
ERROR: You authenticated successfully to *chef server url* as nhudacin but you are not authorized for this action
Response:  missing read permission

I am unable to do these commands as well: 
knife vault update passwords root -S "*:*"
knife vault update passwords root -A "*anyone other than me*"

My question is what permission do I need to ask for on our chef server in order to perform these commands? Does anyone know if this is maybe a search permission with solr? 

Thanks and keep up the great work!

**Comment by jf647** [comment]
In order to encrypt a vault item, you have to have read permission on the public keys for all the admins and for all the clients matching your search query.

I think you have two problems; some of which are manifesting differently for me (using ChefDK 0.6.0, which is knife 12.3.0).  First, the queries ":" and "role:" aren't valid:

```
$  knife vault update foo bar -S ":"
ERROR: The data in your request was invalid
Response: invalid search query: ':'
$  knife vault update foo bar -S "role:"
ERROR: The data in your request was invalid
Response: invalid search query: 'role:'
```

To check if a search query is valid, run it by 'knife search node' first.  If it doesn't pass that, it won't work with vault either.

The fact that you can't encrypt for anyone other than you suggests that the issue is that you can't read the client objects for the other admins.  Are you an admin of your org?  If not, I have good or bad news depending on what version of chef-server you have.

The knife-acl plugin is the only way I know of to let members of group x read the user objects of members of group y.  Unfortunately, it doesn't seem to work properly on Chef Server 12, which Chef have acknowledged.

If you have Chef Server 11, this old issue shows the commands I used to set up read permissions:

https://github.com/Nordstrom/chef-vault/issues/126

If you're on Chef 12, the only solution that we know of is to make the user a member of the admins group, or to manually give them read access to every user and node for whom a vault would be encrypted (which even if you could automate would need to be refreshed every time you bootstrapped a new node or added a new admin user).

Our planned way forward is a combination of the chef_vault_try_notify cookbook:

https://supermarket.chef.io/cookbooks/chef_vault_try_notify

And an upcoming daemon that will read the SNS notifications that the resource produces and refresh the vault.  The initial MVP will probably be very AWS-focused, but I'm going to try to build it with plugins from the first so that people can add support for other messaging systems.  The on_failure block of the resource is just a plain-old-ruby block, so you can currently inject the failure message into whatever messaging system you like (and if you feel like creating a helper for GCE or Azure or whatever platform you use, we'd love a PR to make it more useful out of the box for more people).

**Comment by nhudacin** [comment]
Thank you @jf647. To address the first problem mentioned, the bad queries. This was simply just GitHub not including my asterisks in the quoted strings. Good catch. 

You're correct, at the time of the op, I was not a member of the admin group. I am now and chef-vault is working as expected, without the read permission errors. Maybe just a note in this projects readme to state that a vault can be created by a user but has limited functionality opposed to a vault created by an admin. I don't think being an admin is really a requirement here but has certain properties that may be required in certain implementations. 

Thank you for the tip on chef-vault-try-notify. It addresses some of the pain points I'm working through with auto scaling. I'm definitely going to implement that. At least until knife-windows gets updated to auto refresh before bootstrapping https://github.com/chef/knife-windows/issues/237. 

I would be very interested in contributing to that upcoming daemon. We are working on distributing our primarily windows based architecture between an internal vm ware cloud system and AWS. If windows or VM ware fit into the roadmap, ping me. 

Nick

**Comment by nhudacin** [comment]
I'm closing this issue. @jf647  confirmed that: 

A vault can be created by a chef user and used by that user and any client created by that user. 

In order for a vault to be managed by different users, the creating user must have read access to those other users' public key and read permission to their clients' public keys.
