### ISSUE TITLE
Should warn/error when modifying 1.x items

### ISSUE THREAD

**Issue by moserke** [Nordstrom/chef-vault#52]
When modifying 1.x items instead of blowing up with a .empty? on nil error it should exit gracefully with a meaningful error

**Comment by jf647** [comment]
Detection and warning has been added via this PR:

https://github.com/Nordstrom/chef-vault/pull/173

Automatic fixing is probably doable in 2.7.x, but I don't think we'll ever have a way to set the admins automatically.  Auto-fixing may be a bad idea, because then people might never realize that they need to use `knife vault update` to properly set the admins array.
